### ISSUE TITLE
[Meta] Drop MDBootstrap

### ISSUE THREAD

**Issue by VentGrey** [UpVent/upvent.codes#86]
MDBootstrap, while helping a lot with material design things, has come off to be heavy, monolithic and "off" standards now. 

This "may" be as easy as replacing file or may be not, depending on how much dependency our template files have with mdbootstrap.

This should be done in when the project reaches BETA

**Comment by filipkappa** [comment]
You should check out the latest version - it is updated to the latest Material Design 2.0 guidelines introduced in 2020 and built with the latest Bootstrap 5:
https://mdbootstrap.com/docs/standard/
